export enum MappedsReturnsEnum {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  TOKEN_EXPIRED = 'AUTH_002',
  UNAUTHORIZED = 'AUTH_003',

  // User
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',

  // Conversation
  CONVERSATION_NOT_FOUND = 'CONV_001',
  CONVERSATION_ALREADY_COMPLETED = 'CONV_002',
  CONVERSATION_LIMIT_REACHED = 'CONV_003',

  // Groq
  GROQ_API_ERROR = 'GROQ_001',
  GROQ_TRANSCRIPTION_FAILED = 'GROQ_002',
  GROQ_RATE_LIMIT = 'GROQ_003',

  // Storage
  STORAGE_ERROR = 'STOR_001',
  STORAGE_UPLOAD_FAILED = 'STOR_002',
  INVALID_AUDIO_FORMAT = 'STOR_003',
  FILE_TOO_LARGE = 'STOR_004',

  // Topic
  TOPIC_NOT_FOUND = 'TOPIC_001',

  // RAG
  RAG_SEARCH_FAILED = 'RAG_001',
}
